version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: chatin-server
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./src:/app/usr
  db:
    image: postgres:13-alpine
    container_name: chatin-db
    restart: always
    environment:
      POSTGRES_DB: 'chatin-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-db:/var/lib/postgres-db
