version: '3.3'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: 'chatin-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '54321:5432'
    volumes:
      - ./postgres-db:/var/lib/postgres-db

volumes:
  db:
