version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: chatin-server
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./src:/app/usr