version: '3.8'

services:
  db:
    image: postgres:13.11-alpine
    container_name: chatin-db
    restart: always
    environment:
      POSTGRES_DB: 'chatin-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
